#ifndef EJOY_2D_SHADER_H
#define EJOY_2D_SHADER_H

#define PROGRAM_DEFAULT -1
#define PROGRAM_PICTURE 0
#define PROGRAM_RENDERBUFFER 1
#define PROGRAM_TEXT 2
#define PROGRAM_TEXT_EDGE 3
#define PROGRAM_TRAIL 4

#endif
