#ifndef _EASYEDITOR_EE_TEXTURE_FORMAT_H_
#define _EASYEDITOR_EE_TEXTURE_FORMAT_H_

namespace ee
{

enum EE_TEXTURE_FORMAT {
	EE_TEXTURE_INVALID = 0,
	EE_TEXTURE_RGBA8,
	EE_TEXTURE_RGBA4,
	EE_TEXTURE_RGB,
	EE_TEXTURE_RGB565,
	EE_TEXTURE_A8,
	EE_TEXTURE_DEPTH,	// use for render target
	EE_TEXTURE_PVR2,
	EE_TEXTURE_PVR4,
	EE_TEXTURE_ETC1,
};

}

#endif // _EASYEDITOR_EE_TEXTURE_FORMAT_H_