#ifndef _EASYUI_MESSAGE_ID_H_
#define _EASYUI_MESSAGE_ID_H_

namespace eui
{

enum MSG_ID {
	MSG_QUERY_WINDOW_VIEW_SIZE = 1000,
	MSG_CHANGE_WINDOW_VIEW_SIZE,
	MSG_RESET_VIEWPORT
};

}

#endif // _EASYUI_MESSAGE_ID_H_